# libraries ---------------------------------------------------------------
library("tidyverse")
library("tximport")
library("tximportData")
library("DESeq2")
library("GenomicFeatures")
library("biomaRt")
library("apeglm")
library("IHW")
library("vsn")
library("ComplexHeatmap")
library("RColorBrewer")
library("viridis")
library("PoiClaClu")
library("limma")
library("AnnotationDbi")
library("org.Hs.eg.db")
