# libraries ---------------------------------------------------------------
source(file = "scr/00_library.R")

# metadata ----------------------------------------------------------------
# for htseq-count: a data.frame with three or more columns. Each row describes one sample. The first column is the sample name, the second column the file name of the count file generated by htseq-count, and the remaining columns are sample metadata which will be stored in colData
# NOTICE!!! as to be a data.frame
meta <- read_csv("../../data/LUT_samples.csv")%>%
  data.frame()

# define the model --------------------------------------------------------
clone <- meta$clone
gender <- meta$gender
treat <- factor(meta$treat,levels = c("mock","BMP9"))

# build the design
design <- model.matrix(~ clone + treat)
colnames(design) <- c("intercept","cloneclone_4A","cloneClone_51","cloneClone_70","cloneclone_9C","treatBMP9")

saveRDS(design,file = "../../out/object/design_BMP9.rds")

design_gender <- model.matrix(~ treat*gender)
colnames(design_gender) <- c("intercept","treatBMP9","genderM","intBMP9_M")

saveRDS(design_gender,file = "../../out/object/design_BMP9_gender.rds")

# build the object --------------------------------------------------------
# is keeping only the objext in the lut_sample
ddsHTSeq <- DESeqDataSetFromHTSeqCount(sampleTable = meta,
                                       directory = "../../data/htseq_geneCounts/",
                                       design= design)

saveRDS(ddsHTSeq,file = "../../out/object/ddsHTSeq_BMP9.rds")

ddsHTSeq_gender <- DESeqDataSetFromHTSeqCount(sampleTable = meta,
                                       directory = "../../data/htseq_geneCounts/",
                                       design= design_gender)

saveRDS(ddsHTSeq_gender,file = "../../out/object/ddsHTSeq_BMP9_gender.rds")
